[profile.default]
src = "src"
out = "artifacts"
libs = ["lib"]
remappings = ['@openzeppelin/contracts@5.0.0=lib/openzeppelin-contracts/contracts']

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
